# Generated by Django 5.1.1 on 2024-09-29 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobby.state'),
        ),
    ]
