# Generated by Django 5.1.1 on 2024-10-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobby', '0002_job_applied_job_salary_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.TextField(default=None),
        ),
    ]
