# Generated by Django 5.1.1 on 2024-10-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobby', '0004_job_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.TextField(default=None, unique=True),
        ),
    ]
