# Generated by Django 5.1.1 on 2024-11-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobby', '0005_alter_job_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='salary_end',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_start',
            field=models.FloatField(default=None, null=True),
        ),
    ]
