# Generated by Django 5.1.1 on 2024-11-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobby', '0006_remove_job_salary_job_salary_end_job_salary_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_type',
            field=models.CharField(choices=[('yearly', 'YEARLY'), ('hourly', 'HOURLY')], default=None, null=True),
        ),
    ]
