# Generated by Django 5.1.1 on 2024-11-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobby', '0008_paymenttype_alter_job_payment_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymenttype',
            table='jobby_payment_type',
        ),
    ]
